### ISSUE TITLE
FormikProvider e formik bag no formulário

### ISSUE THREAD

**Issue by lalizita** [React-Bootcamp-WoMarkersCode/certificate-generator#23]
Todas essas propriedades de componente que estão no <Form/> como initial values vocês devem mudar para dentro de um **formikbag** com o hook useFormik

https://github.com/React-Bootcamp-WoMarkersCode/certificate-generator/blob/121cf9c7b1a70fa8b8c9523d508915254ff009c1/certificate/src/components/form-login/index.js#L14

ficará mais ou menos assim

```
import { useFormik, FormikPRovider } from 'formik'

const formikbag = useFormik({
  initialValues:{
      remember: true,
   }
  onSubmit:onFinish
})


<FormikProvider value={formikbag}>
    //Form do ant
     <Form>
       {...}
     </Form>
</FormikProvider>
```

um exemplo para ter base 
https://github.com/lalizita/credit-card-form/blob/master/src/components/CreditCardForm/CreditCardForm.js#L31

**Comment by ahakawa** [comment]
Não tô conseguindo fazer a validação :(

`import React from 'react';
import { Form, Input, Button } from 'antd';
import { UserOutlined, LockOutlined } from '@ant-design/icons';
import { useFormik, FormikProvider} from 'formik'
import * as Yup from 'yup';


const FormLogin = () => {

  const onFinish = values => {
    console.log('Received values of form: ', values);
  };

  const formikbag = useFormik ({
    initialValues: {
      email: "",
      password: ""
    },
    validationSchema: Yup.object({
      email: Yup.string().email('Email inválido').required('Required'),
      password: Yup.string().min(8).required()
  }),
    onSubmit:onFinish
   
  })
 
  
  

  //O article está sendo utilizado do tachyons para colocar na formatação dos campos e a centralização na tela e a sombra
  return (
  <FormikProvider values={formikbag}>
	<article class="mw5 center bg-white shadow-5 br3 pa3 pa4-ns mv3 ba b--black-10">
    <Form className="login-form" onSubmit={formikbag.handleSubmit}>
      <Form.Item name="email">
        <Input name="email" prefix={<UserOutlined className="site-form-item-icon" />} placeholder="Email" />
      </Form.Item>
      <Form.Item name="password">
        <Input name="password" prefix={<LockOutlined className="site-form-item-icon" />} type="password"placeholder="Senha" />
      </Form.Item>
      <Form.Item>
        <a className="login-form-forgot" href="">
          Esqueci a senha
        </a>
      </Form.Item>

      <Form.Item>
        <Button type="primary" style={{background:'#C6255A', 'border-color': '#C6255A', 'margin-right':'15%'}} htmlType="submit" className="login-form-button">
          Entrar
        </Button>
        <a href="">Registrar-se!</a>
      </Form.Item>
    </Form>
	</article>
  </FormikProvider>
	
  );
};

export default FormLogin;`

**Comment by ahakawa** [comment]
Issue resolvida usando somente formik e getFieldProps
